### ISSUE TITLE
npm build issue

### ISSUE THREAD

**Issue by Otacon-404** [franfdezmorales/interact#1]
when i use the source code and run all the npm commands the eye dose not work even without changing anything in ui folder

**Comment by franfdezmorales** [comment]
> cuando uso el código fuente y ejecuto todos los comandos npm, la dosis del ojo no funciona incluso sin cambiar nada en la carpeta ui

Probably because you need to change the path of scripts on dist/index.html, just change /[...].js to ./[...].js

**Comment by franfdezmorales** [comment]
> when i use the source code and run all the npm commands the eye dose not work even without changing anything in ui folder

Probably because you need to change the path of scripts on dist/index.html, just change /[...].js to ./[...].js

**Comment by Otacon-404** [comment]
thank you. that fixed the problem
